name: Release

on:
  workflow_run:
    workflows: ["Tag version"]
    types:
      - completed

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Check for tag on commit
        id: tag
        run: |
          git fetch --tags
          tag=$(git tag --points-at ${{ github.event.workflow_run.head_sha }} | grep '^v' | head -n 1)
          if [ -n "$tag" ]; then
            echo "tag=$tag" >> "$GITHUB_OUTPUT"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
      - run: git checkout "${{ steps.tag.outputs.tag }}"
        if: steps.tag.outputs.exists == 'true'
      - uses: astral-sh/setup-uv@v4
        if: steps.tag.outputs.exists == 'true'
        with:
          python-version: "3.11"
      - run: uv build
        if: steps.tag.outputs.exists == 'true'
      - run: uv publish --check-url https://pypi.org/simple
        if: steps.tag.outputs.exists == 'true'
      - name: Create GitHub release
        if: steps.tag.outputs.exists == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
